delivery-service:
  message: "Welcome to FoodApp Delivery APIs Dev support"
  contactDetails:
    name: "Sayan Mallick - Lead Dev"
    email: "Sayan.Mallick@foodApp.com"
    onCallSupport:
      - (453) 392-4829
      - (236) 203-0384
build:
  version: 1.1.0
   